# Generated by Django 5.1 on 2024-09-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('motdepasse', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, choices=[('client', 'Client'), ('fournisseur', 'Fournisseur')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('type_fournisseur', models.CharField(blank=True, choices=[('direct', 'Direct'), ('indirect', 'Indirect')], max_length=10, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('seuil_critique', models.IntegerField(default=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Préventive'), ('curative', 'Curative')], max_length=10)),
                ('description', models.TextField()),
                ('date_planifiee', models.DateField(blank=True, null=True)),
                ('date_intervention', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateField(auto_now_add=True)),
                ('quantite_avant', models.IntegerField()),
                ('quantite_apres', models.IntegerField()),
                ('type_changement', models.CharField(choices=[('ajout', 'Ajout'), ('retrait', 'Retrait')], max_length=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateField(auto_now_add=True)),
                ('ancien_prix', models.FloatField()),
                ('nouveau_prix', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.produit')),
            ],
        ),
    ]
